### ISSUE TITLE
Issue while writing to S3 from Spark

### ISSUE THREAD

**Issue by jashradia** [uprush/kube-spark#2]
I am facing an issue while writing the output to S3 from spark on EKS. The EKS cluster and compute nodes have full S3 access. when i perform aws s3 cp from one of the nodes to S3(write), it is working fine in CLI. 

I have followed this methodology mentioned in this article [https://towardsdatascience.com/apache-spark-with-kubernetes-and-fast-s3-access-27e64eb14e0f](url) and used uprush spark image 2.4.6 from docker hub

This is the code snippet:
`
from pyspark.sql import SparkSession

spark = SparkSession\
        .builder\
        .appName("s3_test")\
		.config("spark.hadoop.fs.s3a.aws.credentials.provider","com.amazonaws.auth.InstanceProfileCredentialsProvider") \
		.config("spark.hadoop.fs.s3a.path.style.access","true") \
        .getOrCreate()

spark._jsc.hadoopConfiguration().set("com.amazonaws.services.s3.enableV4", "true")
spark._jsc.hadoopConfiguration().set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
spark._jsc.hadoopConfiguration().set("fs.s3a.aws.credentials.provider", "com.amazonaws.auth.InstanceProfileCredentialsProvider,com.amazonaws.auth.DefaultAWSCredentialsProviderChain")
spark._jsc.hadoopConfiguration().set("fs.AbstractFileSystem.s3a.impl", "org.apache.hadoop.fs.s3a.S3A")

df = spark.read.parquet("s3a://aws-a0049-use1-00-d-s3b-bpod-bdp-data01/SparkKubernetesPOC/part-00000-668d3b32-fbd8-49e8-8087-697725839725-c000")
df.count()
df.show()
df.printSchema()
import os 
df.write.csv("s3a://aws-a0049-use1-00-d-s3b-bpod-bdp-data01/SparkKubernetesPOC/test_output.csv")

spark.stop()

`

i am getting following error:

2020-08-12 17:39:07,311 INFO datasources.FileSourceStrategy: Pruning directories with:
2020-08-12 17:39:07,312 INFO datasources.FileSourceStrategy: Post-Scan Filters:
2020-08-12 17:39:07,312 INFO datasources.FileSourceStrategy: Output Data Schema: struct<abbott_customer_id: string, customer_type: string, salesforce: string, prescriber_status: string, source_system_id: string ... 3 more fields>
2020-08-12 17:39:07,312 INFO execution.FileSourceScanExec: Pushed Filters:
Traceback (most recent call last):
  File "/tmp/spark-0ac7ac4e-9479-486a-a878-c6fd284f77cd/s3_test.py", line 22, in <module>
    df.write.csv("s3a://aws-a0049-use1-00-d-s3b-bpod-bdp-data01/SparkKubernetesPOC/test_output.csv")
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 932, in csv
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o65.csv.
: java.nio.file.AccessDeniedException: s3a://aws-a0049-use1-00-d-s3b-bpod-bdp-data01/SparkKubernetesPOC/test_output.csv: getFileStatus on s3a://aws-a0049-use1-00-d-s3b-bpod-bdp-data01/SparkKubernetesPOC/test_output.csv: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 1904C1E2E97E1231; S3 Extended Request ID: IT8U+DzbEm4jGKMnOcAc/SdjyXJSKl4HIfyCQSVfzOtwl2CW7kpdwlDmXcu9c9K2yzw/jt0mEn8=), S3 Extended Request ID: IT8U+DzbEm4jGKMnOcAc/SdjyXJSKl4HIfyCQSVfzOtwl2CW7kpdwlDmXcu9c9K2yzw/jt0mEn8=:403 Forbidden
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:230)
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:151)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2239)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:2204)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:2143)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.exists(S3AFileSystem.java:3031)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:93)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:677)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:677)
        at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:677)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:286)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:272)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:230)
        at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:665)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 1904C1E2E97E1231; S3 Extended Request ID: IT8U+DzbEm4jGKMnOcAc/SdjyXJSKl4HIfyCQSVfzOtwl2CW7kpdwlDmXcu9c9K2yzw/jt0mEn8=), S3 Extended Request ID: IT8U+DzbEm4jGKMnOcAc/SdjyXJSKl4HIfyCQSVfzOtwl2CW7kpdwlDmXcu9c9K2yzw/jt0mEn8=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1640)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4368)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4315)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1271)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$4(S3AFileSystem.java:1290)
        at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
        at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:285)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:1287)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2224)
        ... 37 more

2020-08-12 17:39:07,426 INFO spark.SparkContext: Invoking stop() from shutdown hook
2020-08-12 17:39:07,431 INFO server.AbstractConnector: Stopped Spark@783c0863{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2020-08-12 17:39:07,435 INFO ui.SparkUI: Stopped Spark web UI at http://spark-pi-072b2773e3c0b94e-driver-svc.default.svc:4040
2020-08-12 17:39:07,438 INFO k8s.KubernetesClusterSchedulerBackend: Shutting down all executors
2020-08-12 17:39:07,439 INFO k8s.KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asking each executor to shut down
2020-08-12 17:39:07,447 WARN k8s.ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed (this is expected if the application is shutting down.)
2020-08-12 17:39:07,534 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
2020-08-12 17:39:07,558 INFO memory.MemoryStore: MemoryStore cleared
2020-08-12 17:39:07,559 INFO storage.BlockManager: BlockManager stopped
2020-08-12 17:39:07,564 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
2020-08-12 17:39:07,569 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
2020-08-12 17:39:07,577 INFO spark.SparkContext: Successfully stopped SparkContext
2020-08-12 17:39:07,577 INFO util.ShutdownHookManager: Shutdown hook called
2020-08-12 17:39:07,579 INFO util.ShutdownHookManager: Deleting directory /var/data/spark-5b678cb3-ba02-4c74-a717-e7d98876eacc/spark-1c307a58-bf74-4238-bbd9-4b282d3da1ff/pyspark-eee7bf84-2174-4347-9842-e054b24884a6
2020-08-12 17:39:07,582 INFO util.ShutdownHookManager: Deleting directory /var/data/spark-5b678cb3-ba02-4c74-a717-e7d98876eacc/spark-1c307a58-bf74-4238-bbd9-4b282d3da1ff
2020-08-12 17:39:07,586 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-0ac7ac4e-9479-486a-a878-c6fd284f77cd
2020-08-12 17:39:07,592 INFO impl.MetricsSystemImpl: Stopping s3a-file-system metrics system...
2020-08-12 17:39:07,592 INFO impl.MetricsSystemImpl: s3a-file-system metrics system stopped.
2020-08-12 17:39:07,592 INFO impl.MetricsSystemImpl: s3a-file-system metrics system shutdown complete.

**Comment by uprush** [comment]
This looks like an authentication error. I am not sure how AWS instance profile works from within a container, you may want to check whether you can do aws s3 cp from within the container.

**Comment by jashradia** [comment]
When I tried doing so in the code i am submitting, I got error that AWS command is not found. How do I create the image with AWS CLI installed? (I am new to docker, so it is not so straight forward for me)

Also, I have given full S3 permission to these roles:
Account from which the cluster was created (kubectl)
EKS Cluster role
EKS Compute node role

Do you have any idea which role is used by the container?

**Comment by jashradia** [comment]
There was an issue from IAM side. container does inherit all the permissions of compute nodes, but it did not have to list buckets. that's why aws cp was working but when we tried ls, it was not working. 
Spark gets the file status before writing to S3, so due to that job was failing. 
Closing this issue.
